# Generated by Django 4.0.6 on 2022-07-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('loc', models.CharField(choices=[('bahawalpur', 'Bahawalpur'), ('lahore', 'Lahore'), ('islamabad', 'Islamabad'), ('karachi', 'Karachi')], max_length=50)),
                ('gender', models.CharField(max_length=100)),
                ('pjl', models.CharField(max_length=100)),
                ('pimage', models.ImageField(blank=True, upload_to='pimages')),
                ('file', models.FileField(blank=True, upload_to='fileDoc')),
            ],
        ),
    ]
